#Server setting (ServerProperties)
server:
  port: 8080
  sessionTimeout: 30

#
spring:
  profiles:
    active: local
  datasource:
    url : jdbc:mysql://localhost:3306/cbb
    username : cbb
    password : cbb
    driverClassName : com.mysql.jdbc.Driver
    #jpa   setting
  jpa:
   database: mysql
   show-sql: true
   properties:
         hibernate:
           dialect: org.hibernate.dialect.MySQL5Dialect
  dubbo:
   appname: cbec-inbound-application
   registry: zookeeper://127.0.0.1:2181
   protocol: dubbo
   port: 2080
   threads: 200

  # thymeleaf
thymeleaf:
  prefix: classpath:/templates/
  #开发时关闭缓存,不然没法看到实时页面
  cache: false
  mode: HTML5
  encoding: utf-8
  content-type: text/html


   # Mybatis setting
mybatis:
   config-location: classpath:mybatis/mybatis-config.xml
   ## 目前不知道什么原因，mapper-locations 这种方式不能加载xml 文件
   mapperLocations: classpath:mybatis/mapper/system/StudentMapper.xml

